import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/actions/redux/provider";
import { auth } from '@/auth'
import { SessionProvider } from 'next-auth/react'
import { APP_NAME } from '../constants/index';
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `${APP_NAME}`,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <title>CommuneSphere</title>
        <body className={inter.className}>
          <Providers>
            <EdgeStoreProvider>
              {children}
            </EdgeStoreProvider>
          </Providers>
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
